version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - data_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

  couchdb:
    image: couchdb:latest
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - data_couchdb:/opt/couchdb/data
    restart: unless-stopped
    networks:
      - backend

  neo4j:
    image: neo4j:latest
    volumes:
      - data_neo4j_logs:/logs
      - data_neo4j_config:/config
      - data_neo4j_data:/data
      - data_neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data_postgres:
    driver: local
  data_couchdb:
    driver: local
  data_neo4j_logs:
    driver: local
  data_neo4j_config:
    driver: local
  data_neo4j_data:
    driver: local
  data_neo4j_plugins:
    driver: local
